<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE dwwm_2021 [
    <!ELEMENT <dwwm_2021> (prenom+, nom, age, genre?, site_perso?, info_confinement, info_dev)>
    <!-- DTD pour la civilité -->
    <!ELEMENT prenom (#PCDATA)>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT genre (masculin|feminin) >
    <!ELEMENT masculin EMPTY >
    <!ELEMENT feminin EMPTY >
    <!ELEMENT site_perso (#PCDATA)>
    <!-- DTD pour le confinement-->
    <!ELEMENT info_confinement (nombre_de_personne, lieu)>
    <!ELEMENT nombre_de_personne (nombre_adulte, nombre_enfant?)>
    <!ELEMENT nombre_adulte (#PCDATA)>
    <!ELEMENT nombre_enfant (#PCDATA)>
    <!ELEMENT lieu (commune, type, surface, jardin)>
    <!ELEMENT commune (#PCDATA)>
    <!ELEMENT type (#PCDATA) >
    <!ELEMENT surface (#PCDATA) >
    <!ELEMENT jardin (jardin_presence, jardin_surface?) >
    <!ELEMENT jardin_presence (#PCDATA)>
    <!ELEMENT jardin_surface (#PCDATA) >
    <!-- DTD pour lales infos de dev -->
    <!ELEMENT info_dev (langage_deja_utilise*, nombre_de_site_developpe?, exemple_de_site_developpe?)>
    <!ELEMENT langage_deja_utilise (XML | HTML | CSS | SASS | LESSCSS | BOOTSTRAP | MATERIALIZE | FOUNDATION | JS | TYPESCRIPT | COFFEESCRIPT | JQUERY | ANGULARJS | NODEJS | REACTJS | VUEJS | ANGULAR | PHP | SYMFONY | LARAVEL | WORDPRESS )*>
    <!ELEMENT XML EMPTY >
    <!ELEMENT HTML EMPTY >
    <!ELEMENT CSS EMPTY >
    <!ELEMENT SASS EMPTY >
    <!ELEMENT LESSCSS EMPTY >
    <!ELEMENT BOOTSTRAP EMPTY >
    <!ELEMENT MATERIALIZE EMPTY >
    <!ELEMENT FOUNDATION EMPTY >
    <!ELEMENT JS EMPTY >
    <!ELEMENT TYPESCRIPT EMPTY >
    <!ELEMENT COFFEESCRIPT EMPTY >
    <!ELEMENT JQUERY EMPTY >
    <!ELEMENT ANGULARJS EMPTY >
    <!ELEMENT NODEJS EMPTY >
    <!ELEMENT REACTJS EMPTY >
    <!ELEMENT VUEJS EMPTY >
    <!ELEMENT ANGULAR EMPTY >
    <!ELEMENT PHP EMPTY >
    <!ELEMENT SYMFONY EMPTY >
    <!ELEMENT LARAVEL EMPTY >
    <!ELEMENT WORDPRESS EMPTY >
    <!ELEMENT nombre_de_site_developpe (#PCDATA) >
    <!ELEMENT exemple_de_site_developpe (#PCDATA) >
]>

<dwwm_2021>
    <!-- civilité -->
    <prenom>Jim</prenom>
    <nom>Mounet</nom>
    <age>29</age>
    <genre>
        <masculin />
    </genre>
    <!-- confinement de 2021-->
    <info_confinement>
        <nombre_de_personne>
            <nombre_adulte>1</nombre_adulte>
        </nombre_de_personne>
        <lieu>
            <commune>St-Priest-en-Jarez</commune>
            <type>Appartement</type>
            <surface>40</surface>
            <jardin>
                <jardin_presence>Non</jardin_presence>
            </jardin>
        </lieu>
    </info_confinement>
    <!-- infos de dev -->
    <info_dev>
        <langage_deja_utilise>
            <HTML />
            <CSS />
        </langage_deja_utilise>
    </info_dev>
</dwwm_2021>










<dwwm_2021>
    <!-- civilité -->
    <prenom>Grégory</prenom>
    <prenom>Bernard</prenom>
    <prenom>Francis</prenom>
    <nom>Desplaces</nom>
    <age>42</age>
    <genre>
        <masculin />
    </genre>
    <site_perso>https://www.gregdesplaces.com</site_perso>
    <!-- confinement de 2021 -->
    <info_confinement>
        <nombre_de_personne>
            <nb_adulte>2</nb_adulte>
        </nombre_de_personne>
        <lieu>
            <commune>Retournac</commune>
            <type>Maison</type>
            <surface>120</surface>
            <jardin>
                <jardin_presence>Oui</jardin_presence>
                <jardin_surface>5000</jardin_surface>
            </jardin>
        </lieu>
    </info_confinement>
    <!-- infos de dev -->
    <info_dev>
        <langage_deja_utilise>
            <HTML />
            <CSS />
            <SASS />
            <LESSCSS />
            <BOOTSTRAP />
            <MATERIALIZE />
            <VUEJS />
            <WORDPRESS />
        </langage_deja_utilise>
        <nombre_de_site_developpe>20+</nombre_de_site_developpe>
    </info_dev>
</dwwm_2021>
